[build]
  command = "npm run netlify:build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200
